export const MLB = {
  122: 'Houston Astros',
  138: 'Colorado Rockies',
  126: 'Washington Nationals',
  137: 'Los Angeles Dodgers',
  114: 'New York Yankees',
  140: 'Arizona Diamondbacks',
  120: 'Minnesota Twins',
  113: 'Baltimore Orioles',
  116: 'Cleveland Indians',
  134: 'Milwaukee Brewers',
  115: 'Tampa Bay Rays',
  131: 'Chicago Cubs',
  133: 'St. Louis Cardinals',
  121: 'Texas Rangers',
  124: 'Los Angeles Angels',
  119: 'Chicago White Sox',
  135: 'Cincinnati Reds',
  112: 'Toronto Blue Jays',
  117: 'Detroit Tigers',
  132: 'Pittsburgh Pirates',
  127: 'New York Mets',
  130: 'Atlanta Braves',
  123: 'Seattle Mariners',
  125: 'Oakland Mariners',
  118: 'Kansas City Royals',
  136: 'San Francisco Giants',
  128: 'Miami Marlins',
  139: 'San Diego Padres',
  129: 'Philadelphia Phillies'
};

export const NBA = {
  81: 'Toronto Raptors',
  82: 'Boston Celtics',
  83: 'New York Knicks',
  84: 'Brooklyn Nets',
  85: 'Philadelphia 76ers',
  86: 'Cleveland Cavaliers',
  87: 'Indiana Pacers',
  88: 'Detroit Pistons',
  89: 'Chicago Bulls',
  90: 'Milwaukee Bucks',
  91: 'Atlanta Hawks',
  92: 'Miami Heat',
  93: 'Charlotte Hornets',
  94: 'Washington Wizards',
  95: 'Orlando Magic',
  96: 'Oklahoma City Thunder',
  97: 'Portland Trail Blazers',
  98: 'Utah Jazz',
  99: 'Denver Nuggets',
  100: 'Minnesota Timberwolves',
  101: 'Golden State Warriors',
  102: 'Los Angeles Clippers',
  103: 'Sacramento Kings',
  104: 'Phoenix Suns',
  105: 'Los Angeles Lakers',
  106: 'San Antonio Spurs',
  107: 'Memphis Grizzlies',
  108: 'Dallas Mavericks',
  109: 'Houston Rockets',
  110: 'New Orleans Pelicans'
};

export const NHL = {
  1: 'Tampa Bay Lightning',
  3: 'Carolina Hurricanes',
  4: 'Florida Panthers',
  5: 'Washington Capitals',
  6: 'Philadelphia Flyers',
  7: 'New Jersey Devils',
  8: 'New York Islanders',
  9: 'New York Rangers',
  10: 'Pittsburgh Penguins',
  11: 'Boston Bruins',
  12: 'Toronto Maple Leafs',
  13: 'Ottawa Senators',
  14: 'Montreal Canadiens',
  15: 'Buffalo Sabres',
  16: 'Detroit Red Wings',
  17: 'St. Louis Blues',
  18: 'Nashville Predators',
  19: 'Columbus Blue Jackets',
  20: 'Chicago Blackhawks',
  21: 'Vancouver Canucks',
  22: 'Colorado Avalanche',
  23: 'Calgary Flames',
  24: 'Edmonton Oilers',
  25: 'Minnesota Wild',
  26: 'San Jose Sharks',
  27: 'Dallas Stars',
  28: 'Los Angeles Kings',
  29: 'Anaheim Ducks',
  30: 'Arizona Coyotes',
  47: 'Winnipeg Jets'
};
